<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSTEMP188SOPHIYA" name="Chrome Test3" tests="1" failures="1" timestamp="1 Mar 2017 15:24:50 GMT" time="141.94" errors="0">
  <testcase name="contactCreation" time="44.289" classname="main_page.TestEngine">
    <failure type="exception.CustomException" message="The value TestAutomationis not matched with the given value Test">
      <![CDATA[exception.CustomException: The value TestAutomationis not matched with the given value Test
	at Page_Object_page.contactPage.accountNameVerify(contactPage.java:88)
	at main_page.TestEngine.contactCreation(TestEngine.java:141)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- contactCreation -->
</testsuite> <!-- Chrome Test3 -->
